# Generated by Django 4.0.6 on 2022-07-22 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='P_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50, null=True)),
                ('Last_Name', models.CharField(max_length=50, null=True)),
                ('Username', models.CharField(max_length=50, null=True)),
                ('DOB', models.DateField(null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Password', models.CharField(max_length=120, null=True)),
                ('Mobile_Number', models.CharField(max_length=10, null=True)),
                ('Gender', models.CharField(max_length=20, null=True)),
                ('Government_ID', models.CharField(max_length=50, null=True)),
                ('Gov_ID_Number', models.CharField(max_length=50, null=True)),
                ('Height', models.CharField(max_length=20, null=True)),
                ('Weight', models.CharField(max_length=20, null=True)),
                ('Blood_Group', models.CharField(max_length=10, null=True)),
                ('Patient_Age', models.CharField(max_length=5, null=True)),
                ('Medical_History', models.CharField(default='No Medical History', max_length=250)),
                ('Address', models.CharField(max_length=50, null=True)),
                ('City', models.CharField(max_length=50, null=True)),
                ('State', models.CharField(max_length=50, null=True)),
                ('Country', models.CharField(max_length=50, null=True)),
                ('Pincode', models.CharField(max_length=20, null=True)),
                ('Patient_Status', models.CharField(default='Patient Exists', max_length=30)),
                ('Registered_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='P_Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disease', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='P_Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50, null=True)),
                ('Token', models.CharField(max_length=30, null=True)),
                ('OTP', models.IntegerField(null=True)),
                ('Generated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.p_detail')),
            ],
        ),
        migrations.CreateModel(
            name='P_Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_Status', models.CharField(default='Pending', max_length=50)),
                ('Payment_Time', models.DateTimeField(null=True)),
                ('Patient_Disease', models.CharField(max_length=120, null=True)),
                ('Appointment_Status', models.CharField(default='Pending', max_length=50)),
                ('Appointment_date', models.DateField(null=True)),
                ('Appointment_time', models.CharField(max_length=50, null=True)),
                ('Appointed_Doctor', models.CharField(max_length=50, null=True)),
                ('Diagnosis', models.CharField(max_length=250, null=True)),
                ('Prescription', models.CharField(max_length=250, null=True)),
                ('App_Rej_Reason', models.CharField(default='Not Rejected', max_length=50)),
                ('Appointment_reg_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('Appointment_mod_at', models.DateTimeField(null=True)),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.p_detail')),
            ],
        ),
    ]
